### ISSUE TITLE
Problems with Fishing

### ISSUE THREAD

**Issue by eissceda** [joshiejack/Mariculture#267]
Recently I started with fishbreading and detected some problems. All problems occuried in the modpack I'm currently playing as well as with the test installation (recommended forge-version with the latest version of mariculture(1.2.4.1)).

First the serious problems:
It is possible to put an entire stack of fishes into the fish feeder, causing them to age simultanously and create an extremely large amount of eggs (once their "durability" is at zero one fish dies after each cicle while the number decreases further). Image of this is below.
![fishstack](https://cloud.githubusercontent.com/assets/11756785/6945514/96e38a7e-d89a-11e4-960f-07fab2b746cf.jpg)

The secound thing is that the lifespan of the fishes is kind of broken. All fishes show an lifespan-value of 300 when pressing shift while the description and the fish feeder still show correct values. Additional to this all freshly hatched fishes have a lifespan of 15 what is a real problem since they are kindof useless with such a short lifespan. I'm not really sure about this, but both problems could have the same origion.

Now to the little anoyances. Once a fish feeder was uhloaded from the client-side it shows a strang "tank too small"-message while the fishes are still working. Image of this is bellow. Additionaly most fishes that need other fluids than water complain about salty water while they are happily swimming trough their lava-/ender-/whatever-pools. Both problems are just display-issues, but rather annoying since they make it immposible to see the remaining lifespan of certain fishes.
![tanksize](https://cloud.githubusercontent.com/assets/11756785/6946132/7fb32996-d89e-11e4-9973-efdf8c5cc929.jpg)

**Comment by joshiejack** [comment]
Can you check with the latest versions on: http://joshiejack.uk:8080/

I'm pretty sure I'd fixed the first one. But I don't know if I fixed the latter. (I should have probably released these versions officially by now, but been busy).

**Comment by eissceda** [comment]
I've tested it with build 49 and all problems are still there.

**Comment by joshiejack** [comment]
Alrighty. I'll take a look in these as soon as I have some time for Mariculture.

**Comment by joshiejack** [comment]
Should be fixed in 1.2.4.1a
